### ISSUE TITLE
USD pairs appearing even when alt-coins are disabled 

### ISSUE THREAD

**Issue by rraallvv** [rubykube/peatio-trading-ui#104]
I edited `config/seed/currencies.yml` and disabled all coins except for BTC and USD, but market pairs with USD still appear listed even when those alt-coins are disabled.

![screen shot 2018-09-29 at 10 53 51 am](https://user-images.githubusercontent.com/1840524/46248725-fd0c3780-c3ea-11e8-8c53-cd69256ff3eb.png)

both **peatio** and **peatio-trading-ui** are branch `1-8-stable`

**Comment by pkucherenk0** [comment]
Hello @rraallvv This issue was managed in Branch: 1-9-rc.
https://github.com/rubykube/peatio/commit/b016276a3864e99395e3a46b34d715dcd98e0788
https://github.com/rubykube/peatio/commit/6a5b042afb2e00e1edf9f88fef035cb9e568b395
https://github.com/rubykube/peatio/commit/33792f101d7dcbd4f53a5ec6bdcbc3c7aff72495

**Comment by rraallvv** [comment]
@pkucherenk0  Awesome! I'm closing this then. Any updates/time frame for the stable release?
