### ISSUE TITLE
Ranger not update my orders, my balance (For Users)

### ISSUE THREAD

**Issue by huuhait** [rubykube/peatio-trading-ui#109]
I place a order and not update my order
![image](https://user-images.githubusercontent.com/40519768/47305880-0fc60500-d655-11e8-9586-8ac0359698d8.png)
then refresh
![image](https://user-images.githubusercontent.com/40519768/47305902-1d7b8a80-d655-11e8-950d-7b9fc8cdb127.png)
When fix it :(

**Comment by ianeinser** [comment]
@Thedabest did you solve this error?

**Comment by guru260** [comment]
@Thedabest Did u find solution for this issue? I am facing the same problem

**Comment by omgnotagain** [comment]
same problem form me. and i believe it has something to do with ranger authentication failing.

i can authenticate when i change file jwt_authenticator.rb

`payload, header = JWT.decode(token, @public_key, true, @verify_options)`
to
`payload, header = JWT.decode(token, @public_key, false, @verify_options)`

but orders and balance don't update.

edit:

this will skip verfy options. but after some digging i found in file:
lib/jwt/default_options.rb under ruby-(your-version) there was default algo set to HS256 instead of RS256. I can now Authenticate. But user buy/sell orders do not self update. only after refreshing web. but can't close any open orders even after manual refresh.
