### ISSUE TITLE
page not refresh after bid/ask order created.

### ISSUE THREAD

**Issue by sg552** [rubykube/peatio-trading-ui#19]
peatio, peatio-trading-ui   version: 1.6.0  
ubuntu 16. 

once I placed an ask/bid order, the div on the "top right area" is not reload, and I have to manually press F5 , then I saw the order I created.

the attachement is the area that should auto-refresh. 
![screenshot from 2018-04-09 15-15-01](https://user-images.githubusercontent.com/234533/38484356-e8b4d8b0-3c08-11e8-8e7f-1f9f4196f87d.png)

**Comment by sg552** [comment]
thanks, I will try.

**Comment by shouton** [comment]
I have a same problem.

At first i got an error in my chrome console. Obviously it was caused by a mistake in pusher config.
However, after I fix the problem, the error was solved.  

i checked both server and web browse, there were no error anymore, but the screen was still not refreshed.

in my chrome browse, i got
```javascript
Pusher bind member channel successfully
```

in my server, i got pusher log as below.
```bash
I, [2018-05-29T08:42:29.660054 #1715]  INFO -- : Received: {"member_id":6,"event":"account","data":"{\"balance\":\"1.409\",\"locked\":\"1.581\",\"currency\":\"eth\"}","locale":"en"}
```

any ideas, about how to debug the pusher/slanger?
