### ISSUE TITLE
Trade Issue

### ISSUE THREAD

**Issue by esoftllp** [rubykube/peatio-trading-ui#31]
I have upgraded solution to ver 1.7 and running on Ubuntu.

I have balance in BTCUSD but while placing order i am getting some issues.Please check attached image for more details.

![capture](https://user-images.githubusercontent.com/32095632/39507179-6b1f7604-4dfa-11e8-8cd2-000f16abb7e9.PNG)

**Comment by yivo** [comment]
Hi @esoftllp 

I see your upgrade is not valid since market ID is numeric, it should be string. Please, read upgrade notes again.

Also I see your balance is zero, currently there is a bug with zero balance. Don't worry we will fix it.

Also please use the same versions for Peatio & Trading UI, Peatio 1.6 is not compatible with Trading UI 1.7, as example.

**Comment by esoftllp** [comment]
I have cloned 1.7 branch but i think code is not updated because if you check file 
https://github.com/rubykube/peatio-trading-ui/blob/1-7-stable/app/views/markets/_market_list.html.erb
Line No 45.
It should be                   <%= link_to market.fetch(:name), '/trading/' + market.fetch(:id).to_s %>
but it is using int.Let me know if i am wrong.

Thanks

**Comment by yivo** [comment]
@esoftllp You are wrong. to_s is not required and is buggy here because market ID is STRING, not number. Please do migration correctly.

**Comment by yivo** [comment]
You can browser peatio.trade with working trading UI and markets.
